### ISSUE TITLE
Create queue of tuples,TokenType Enum

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#1]
Create a `TokenizerClass` with `enum TokenType`

> used in #2  #3 #6 

``` C#
public static class Tokenizer
{
    public static enum TokenType{ CELL, OP, NUM, BANANA};
    public static Queue<Tuple<String, Tokenizer.TokenType>> Tokenize(String formula);
    ...
}
```

Create a queue of tuples for us to use as tokens. This will be in `Formula` when we're turning the formula into tokens.

For example:

> used in #3 

``` C#
Queue<Tuple<String, Tokenizer.TokenType>> tokens = Tokenizer.Tokenize(formula);
```

It can probably be placed under `Solve()`

**Comment by zachChilders** [comment]
Would it be useful to have LBANANA RBANANA?

**Comment by tylorhl** [comment]
> Would it be useful to have LBANANA RBANANA?

The BANANA evaluation is handled in Postfix. That's the only point we need it. I don't think it'll be a problem.

**Comment by tylorhl** [comment]
Accidentally took care of this today.
