### ISSUE TITLE
Update Tokenizer to handle negatives

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#11]
Tokenizer needs to take into account negatives. Negatives should just really be appended to the beginning of a CELL or NUM. When handling a negative with BANANA, distribute the negative. The negative use might be able to be tracked by a bool. A so-called isNegative.

3+-2 is <3, NUM> <+, OP> <-2, NUM>
3+-A1 is <3, NUM> <+, OP> <-A1, CELL>
3+-(2+A1) is <3, NUM> <+, OP> <(, BANANA> <-2, NUM> <+, OP> <-A1, CELL>

This is what Zach and I will be planning for when we update our portions of the code.

**Comment by zachChilders** [comment]
This can be did by redoing our parser entirely using a Shift-Replace technique.  It'll be painful and terrible.

**Comment by zachChilders** [comment]
NO.
