### ISSUE TITLE
Check for NullReference 

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#14]
We need to check for NullReference errors. For instance: Referencing a cell with nothing in it.

**Comment by zachChilders** [comment]
Where was this bug?

**Comment by tylorhl** [comment]
We took care of referencing a null cell, but I'm sure there are a couple of other places that will throw NullReferenceExceptions. I'm sure we'll find them.

Best case: They were just in the cell and nowhere else will have them.
