### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#16]
Do we need to do a regex for this? Can't we just check the TokenType?
[Formula.cs - L49](https://github.com/zachChilders/SpreadSheet/blob/master/TinySpreadsheet/TinySpreadsheet/Formula.cs#L49)

Also, for solve(), should we change the return type to a `Double?`? It might give us slightly more room for returning different results. For instance: we return Double.NaN if we determine that there's something mathematically wrong with the given formula, but return null if it's just a string.

I think it's at least worth discussing next time we meet.

**Comment by zachChilders** [comment]
Good catch on the regex.  I refactored it.  Solve is already Double?
