### ISSUE TITLE
Dynamic resizing locks the UI thread.

### ISSUE THREAD

**Issue by zachChilders** [zachChilders/SpreadSheet#17]
Right now resizing works properly, but the way we're doing it causes the UI thread to lock instead of go smoothly. 

A few options we've talked about:
- Using a column/row buffer to hold new rows
- Threading/invoking/I forget the exact name but you know what I'm referring to.
- Adding one row/column at a time at the last possible second.  This could be what Excel is doing.
- Creating many columns or rows ahead of time, and collapsing them until they're needed.

No matter what, the dynamic resizing works.  It just needs some performance improvements.

**Comment by tylorhl** [comment]
Scrolling and adding items improved a good bit in my commit 335c5712b5d62bf07460efc601d88b98f94d0241. But we do still need to put creation on another thread.

Our greatest bottleneck will come with adding new items to the view itself. What we can possibly do is create some number ahead of time, add some to the view as invisible, then as we scroll we make them visible. We might be able to get away with just adding them straight to the view while sitting in a buffer outside of the view.

**Comment by tylorhl** [comment]
Did everything I could. This is probably about as good as we're going to get it right now.
