### ISSUE TITLE
Break up at operators and evaluate types

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#2]
> using #1`Tokenizer.Tokenize()` 

This is what happens in `Tokenizer.Tokenize()`

The formula should be broken up at operators: +-/*() with () being their own `BANANA` and all else being `OPERATOR`.

From there, we are left with things that further need evaluating. We'll need to determine `CELL` and `NUM`.
This part can probably be determined right after you've found a `BANANA` or `OPERATOR`.
###### Example: 13+A1*4+(5-6)/7

1) Read character by character, appending to a string each read until an `OPERATOR` or `BANANA` is reached.
2)

``` C#
Tuple op = new Tuple<String, TokenType>('+', OPERATOR);
String current = "13"; //Operator was hit
if(current != "")
    tokens.Add(new Tuple<String, TokenType>(current, getTokenType(current)));
tokens.Add(op);
```

3) Continue reading and follow this pattern.

**Comment by zachChilders** [comment]
Implemented by @marroyo05
